bug:refractor login form validation error
openMF/online-banking pull request #27
Opened 2021-01-11 19:05 UTC by abhishekkumar08

Whenever we try to login in the app with correct username and password
the login form shows validation error.
It was due to by default, Angular/Material watch formControl's error state not only by ```touched``` but also ```submitted``` status of the form as the code you can see
```
isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean {
  return !!(control && control.invalid && (control.touched || (form && form.submitted)));
                                                                       ^^^^^^^^^^^^^^
}
```
For reason above, you also need to reset the form to ```unsubmitted``` status.

Fixes #26

Fixed behaviour
![Correct_login](https://user-images.githubusercontent.com/59651136/104226581-0d3a6a80-546e-11eb-9568-519587fa0ce1.gif)

2021-01-12 19:10 UTC, manigedit commented
@abhishekkumar08  this PR leads to Regression error. 
Expected behaviour : If wrong credentials are passed, the form should show an error state.
As an enhanced suggestion, try to achieve that the spinner should keep spinning until the dashboard loads.

2021-01-12 19:11 UTC, manigedit requested changes
Refer to the comment in the thread

2021-01-12 21:41 UTC, abhishekkumar08 commented
@manigedit as of now upon wrong credentials the console shows an error but the fields now don't turn red, 

![Online Banking — Mozilla Firefox 2021-01-13 01-47-22(1)](https://user-images.githubusercontent.com/59651136/104377188-13067d80-554c-11eb-80f6-71eec259275a.gif)


I tried adding the formDirective to the form and passed it to the ```login()``` but it's showing the same behaviour as of the current pic, any help would be great on how to implement this correctly. Thanks in advance.

As for the enhancement, I'm looking into it.

2021-01-13 07:21 UTC, manigedit commented
> @manigedit as of now upon wrong credentials the console shows an error but the fields now don't turn red,
> 
> ![Online Banking — Mozilla Firefox 2021-01-13 01-47-22(1)](https://user-images.githubusercontent.com/59651136/104377188-13067d80-554c-11eb-80f6-71eec259275a.gif)
> 
> I tried adding the formDirective to the form and passed it to the `login()` but it's showing the same behaviour as of the current pic, any help would be great on how to implement this correctly. Thanks in advance.
> 
> As for the enhancement, I'm looking into it.

You should a find a way alongside the ngSubmit.

2021-01-13 09:02 UTC, abhishekkumar08 commented
@manigedit Please review this. Thanks!

2021-01-17 21:33 UTC, merged